### ISSUE TITLE
Google Maps instead of CareHere.net

### ISSUE THREAD

**Issue by dalianera** [bohdan-s/WanWay-Tech-S20#3]
Hi all! Thanks for sharing you knowledge!

There's a way to switch "carehere" to "googlemaps" in URL# SMS report from device?

Thanks in advance ^^

**Comment by 0x1234567890** [comment]
Set to Google Maps with 

`LANG,0#`

**Comment by dalianera** [comment]
> Set to Google Maps with 
> 
> `LANG,0#`

So many thanks! Works Great!

**Comment by bohdan-s** [comment]
Made clearer in README ([77273374](https://github.com/bohdan-s/WanWay-Tech-S20/commit/727337405f7232e5d3981f2d7c74c4c703eed57c))
